### ISSUE TITLE
delay attribute (might be) broken

### ISSUE THREAD

**Issue by benjaminweb** [derhuerst/db-zugradar-client#3]
Observation: **db-zugradar-client does not provide for a single train the delay.**

**ex.js**:

``` language: javascript
'use strict'

const zugradar = require('db-zugradar-client')
const positions = zugradar.positions

positions()
.then((trains) => {
    console.log(trains)
})
.catch(console.error)
```

`node ex.js` produces only trains without delay attributes:

```
[ { name: 'IC   512',
    id: '84/268782/18/20/80',
    previousStation:
     { type: 'station',
       id: '8800017',
       name: 'Welkenraedt',
       departure: 1497274630 },
    nextStation:
     { type: 'station',
       id: '8800110',
       name: 'Eupen',
       arrival: 1497275050,
       delay: NaN },
    ...]
```

The [raw data](http://www.apps-bahn.de/bin/livemap/query-livemap.exe/dny?L=vs_livefahrplan&performLocating=1&performFixedLocating=1&look_requesttime=15:42:30&livemapRequest=yes&ts=20170612&) goes like:

`["IC   512",776163651,1371740876,"84/268782/18/20/80","29",2,"","Eupen",[],"Welkenraedt","8800017","Eupen","8800110","12.06.17","-1",null,"15:44","15:37",null,null,"4",null,null]
`

Did
a. DB change the data format?
b. DB not change the data format yet only does not provide the delays?
c. happen something different than a. or b.?

**Comment by derhuerst** [comment]
Seems like a bug, will look into it. See also https://media.ccc.de/v/MRMCD15-6986-i_like_trains#video&t=0 for details.

**Comment by derhuerst** [comment]
Seems like DB mostly returns empty delays. But as of ceb4dc1, it will now return `null` instead of `NaN` in this case.
